version: '3.8'

services:
  mp3-extractor:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
